export const EXERCISE_GIFS: Record<string, any> = {
  'ex-ab-rollout': require('../../../assets/workouts/Ab Rollout.gif'),
  'ex-arnold-press': require('../../../assets/workouts/Arnold Press.gif'),
  'ex-bb-curl': require('../../../assets/workouts/Barbell Curl.gif'),
  'ex-bench-press': require('../../../assets/workouts/Barbell Bench Press.gif'),
  'ex-bent-rows': require('../../../assets/workouts/Bent Over Rows.webp'),
  'ex-bulgarian': require('../../../assets/workouts/Bulgarian Split Squat.gif'),
  'ex-cable-cross': require('../../../assets/workouts/Cable Crossovers.gif'),
  'ex-cable-crunch': require('../../../assets/workouts/Cable Crunch.gif'),
  'ex-calf-raise': require('../../../assets/workouts/Calf Raise.webp'),
  'ex-chest-dips': require('../../../assets/workouts/Chest Dips.webp'),
  'ex-chinups': require('../../../assets/workouts/Chin Ups.gif'),
  'ex-concentration': require('../../../assets/workouts/Concentration Curl.gif'),
  'ex-cycling': require('../../../assets/workouts/Cycling.png'),
  'ex-db-fly': require('../../../assets/workouts/Dumbbell Fly.gif'),
  'ex-deadlift': require('../../../assets/workouts/Deadlift.gif'),
  'ex-decline-bench': require('../../../assets/workouts/Decline Bench Press.gif'),
  'ex-elliptical': require('../../../assets/workouts/Elliptical.gif'),
  'ex-face-pull': require('../../../assets/workouts/Face Pull.gif'),
  'ex-front-raise': require('../../../assets/workouts/Front Raise.gif'),
  'ex-hack-squat': require('../../../assets/workouts/Hack Squat.gif'),
  'ex-hammer-curl': require('../../../assets/workouts/Hammer Curl.gif'),
  'ex-hanging-raise': require('../../../assets/workouts/Hanging Leg Raise.gif'),
  'ex-incline-db': require('../../../assets/workouts/Incline Dumbbell Press.gif'),
  'ex-jump-rope': require('../../../assets/workouts/Jump Rope.jpg'),
  'ex-lat-pulldown': require('../../../assets/workouts/Lat Pulldown.gif'),
  'ex-lateral-raise': require('../../../assets/workouts/Lateral Raise.gif'),
  'ex-leg-curl': require('../../../assets/workouts/Leg Curl.gif'),
  'ex-leg-ext': require('../../../assets/workouts/Leg Extension.gif'),
  'ex-leg-press': require('../../../assets/workouts/Leg Press.gif'),
  'ex-lunges': require('../../../assets/workouts/Lunges.gif'),
  'ex-ohp': require('../../../assets/workouts/Overhead Press.gif'),
  'ex-overhead-ext': require('../../../assets/workouts/Overhead Tricep Extension.gif'),
  'ex-plank': require('../../../assets/workouts/Plank.jpg'),
  'ex-preacher-curl': require('../../../assets/workouts/Preacher Curl.gif'),
  'ex-pull-ups': require('../../../assets/workouts/Pull Ups.webp'),
  'ex-rdl': require('../../../assets/workouts/Romanian Deadlift.webp'),
  'ex-rear-delt-fly': require('../../../assets/workouts/Rear Delt Fly.gif'),
  'ex-rowing': require('../../../assets/workouts/Rowing Machine.gif'),
  'ex-seated-row': require('../../../assets/workouts/Seated Cable Row.gif'),
  'ex-skull-crusher': require('../../../assets/workouts/Skull Crushers.jpg'),
  'ex-squat': require('../../../assets/workouts/Barbell Squat.gif'),
  'ex-stairmaster': require('../../../assets/workouts/Stairmaster.gif'),
  'ex-tbar-row': require('../../../assets/workouts/t-bar-rows.gif'),
  'ex-treadmill': require('../../../assets/workouts/Treadmill Run.webp'),
  'ex-tri-dips': require('../../../assets/workouts/Tricep Dips.gif'),
  'ex-tri-pushdown': require('../../../assets/workouts/Tricep Pushdown.gif')
};